# Generated by Django 2.1.1 on 2018-09-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20180919_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='tstart_time',
            field=models.DateTimeField(verbose_name='工单创建时间'),
        ),
    ]
