# Generated by Django 2.1.1 on 2018-09-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_tickets_tsup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='tcontent',
            field=models.TextField(verbose_name='工单内容'),
        ),
    ]
