# Generated by Django 2.1.1 on 2018-09-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20180920_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='tsup_type',
            field=models.CharField(default='远程支持', max_length=32, verbose_name='支持方式'),
            preserve_default=False,
        ),
    ]
