# Generated by Django 2.1.1 on 2018-09-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20180920_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='ttimeused',
            field=models.FloatField(blank=True, null=True, verbose_name='耗时'),
        ),
    ]
